const roomsSection = {
    rooms: [
        {
            id: 0,
            dataTarget: "modal-guest-house",
            name: "Guest House",
            thumbnail: "images/guestHouse/thumbnail.jpg",
            numberOfRoom: "4 rooms",
            numberOfRoomModal: "4 rooms",
            numberOfGuest: "1-2 Guests",
            roomSize: "12 m",
            bed: "1 Double Bed/1 Trundle Bed",
            description: "Nulla vel metus scelerisque ante sollicitudin. Fusce condimentum nunc ac nisi vulputate fringilla.",
            images: [
                {
                    imageId: 0,
                    imageActive: true,
                    imagePath: "images/guestHouse/guestHouse1.jpg",
                },
                {
                    imageId: 1,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse2.jpg"
                },
                {
                    imageId: 2,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse3.jpg",
                },
                {
                    imageId: 3,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse4.jpg",
                },
                {
                    imageId: 4,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse5.jpg",
                },
                {
                    imageId: 5,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse6.jpg",
                },
                {
                    imageId: 6,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse7.jpeg",
                },
                {
                    imageId: 7,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse8.jpg",
                },
                {
                    imageId: 8,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse9.jpg",
                },
                {
                    imageId: 9,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse10.jpg",
                },
                {
                    imageId: 10,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse11.jpeg",
                },
                {
                    imageId: 11,
                    imageActive: false,
                    imagePath: "images/guestHouse/guestHouse12.jpeg",
                },
            ],
            facilities: "<h3>Kitchen</h3><h3>Private Bathroom</h3><h3>Parking Lot</h3><h3>Internet</h3><h3>Security System</h3><h3>Central City Location</h3>",
            address: "<p>Gg. Kenari Indah I, Miliran UH 2, D.I. Yogyakarta</p>",
            mapEmbed: "<div class=\"d-flex\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2607.9399978461915!2d110.38991624692304!3d-7.800622005731553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a577ca4f128dd%3A0xf2814706b60fe93!2sGg.%20Kenari%20Indah%20I%2C%20Muja%20Muju%2C%20Kec.%20Umbulharjo%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta%2055165!5e0!3m2!1sen!2sid!4v1718864226541!5m2!1sen!2sid\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe></div>",
        },

        {
            id: 1,
            dataTarget: "modal-guest-house-vip",
            name: "Guest House VIP",
            thumbnail: "images/guestHouseVIP/thumbnail.jpg",
            numberOfRoom: "1 room",
            numberOfRoomModal: "1 room",
            numberOfGuest: "1-2 Guests",
            roomSize: "12 m",
            bed: "1 Queen Bed",
            description: "Nulla vel metus scelerisque ante sollicitudin. Fusce condimentum nunc ac nisi vulputate fringilla.",
            images: [
                {
                    imageId: 0,
                    imageActive: true,
                    imagePath: "images/guestHouseVIP/guestHouseVIP1.jpg",
                },
                {
                    imageId: 1,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP2.jpg"
                },
                {
                    imageId: 2,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP3.jpg",
                },
                {
                    imageId: 3,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP4.jpg",
                },
                {
                    imageId: 4,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP5.jpg",
                },
                {
                    imageId: 5,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP6.jpg",
                },
                {
                    imageId: 6,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP7.jpg",
                },
                {
                    imageId: 7,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP8.jpg",
                },
                {
                    imageId: 8,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP9.jpg",
                },
                {
                    imageId: 9,
                    imageActive: false,
                    imagePath: "images/guestHouseVIP/guestHouseVIP10.jpg",
                },
            ],
            facilities: "<h3>Kitchen</h3><h3>Private Bathroom</h3><h3>Parking Lot</h3><h3>Internet</h3><h3>Security System</h3><h3>Central City Location</h3>",
            address: "<p>Gg. Kenari Indah I, Miliran UH 2, D.I. Yogyakarta</p>",
            mapEmbed: "<div class=\"d-flex\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2607.9399978461915!2d110.38991624692304!3d-7.800622005731553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a577ca4f128dd%3A0xf2814706b60fe93!2sGg.%20Kenari%20Indah%20I%2C%20Muja%20Muju%2C%20Kec.%20Umbulharjo%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta%2055165!5e0!3m2!1sen!2sid!4v1718864226541!5m2!1sen!2sid\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe></div>",
        },

        {
            id: 2,
            dataTarget: "modal-woman-dormitory",
            name: "Woman Dormitory",
            thumbnail: "images/dormitory/thumbnail.jpeg",
            numberOfRoom: "10 rooms",
            numberOfRoomModal: "10 rooms",
            numberOfGuest: "1 Guest",
            roomSize: "9 m",
            bed: "1 Multifunctional Bed",
            description: "Nulla vel metus scelerisque ante sollicitudin. Fusce condimentum nunc ac nisi vulputate fringilla.",
            images: [
                {
                    imageId: 0,
                    imageActive: true,
                    imagePath: "images/dormitory/dormitory1.jpeg",
                },
                {
                    imageId: 1,
                    imageActive: false,
                    imagePath: "images/dormitory/dormitory2.jpeg"
                },
                {
                    imageId: 2,
                    imageActive: false,
                    imagePath: "images/dormitory/dormitory3.jpeg",
                },
                {
                    imageId: 3,
                    imageActive: false,
                    imagePath: "images/dormitory/dormitory4.jpeg",
                },
                {
                    imageId: 4,
                    imageActive: false,
                    imagePath: "images/dormitory/dormitory5.jpeg",
                },
            ],
            facilities: "<h3>Kitchen</h3><h3>Private Bathroom</h3><h3>Parking Lot</h3><h3>Internet</h3><h3>Security System</h3><h3>Central City Location</h3>",
            address: "<p>Gg. Kenari Indah I, Miliran UH 2, D.I. Yogyakarta</p>",
            mapEmbed: "<div class=\"d-flex\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2607.9399978461915!2d110.38991624692304!3d-7.800622005731553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a577ca4f128dd%3A0xf2814706b60fe93!2sGg.%20Kenari%20Indah%20I%2C%20Muja%20Muju%2C%20Kec.%20Umbulharjo%2C%20Kota%20Yogyakarta%2C%20Daerah%20Istimewa%20Yogyakarta%2055165!5e0!3m2!1sen!2sid!4v1718864226541!5m2!1sen!2sid\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe></div>",
        },

        {
            id: 3,
            dataTarget: "modal-apartment",
            name: "Apartment (Jakarta)",
            thumbnail: "images/apartment/thumbnail.jpeg",
            numberOfRoom: "1 unit apartment",
            numberOfRoomModal: "1 bedroom & 1 bathroom",
            numberOfGuest: "1-2 Guests",
            roomSize: "51 m",
            bed: "1 Multifunctional Bed",
            description: "Nulla vel metus scelerisque ante sollicitudin. Fusce condimentum nunc ac nisi vulputate fringilla.",
            images: [
                {
                    imageId: 0,
                    imageActive: true,
                    imagePath: "images/apartment/apartment1.jpeg",
                },
                {
                    imageId: 1,
                    imageActive: false,
                    imagePath: "images/apartment/apartment2.jpeg"
                },
                {
                    imageId: 2,
                    imageActive: false,
                    imagePath: "images/apartment/apartment3.jpeg",
                },
                {
                    imageId: 3,
                    imageActive: false,
                    imagePath: "images/apartment/apartment4.jpeg",
                },
                {
                    imageId: 4,
                    imageActive: false,
                    imagePath: "images/apartment/apartment5.jpeg",
                },
                {
                    imageId: 5,
                    imageActive: false,
                    imagePath: "images/apartment/apartment6.jpeg",
                },
                {
                    imageId: 6,
                    imageActive: false,
                    imagePath: "images/apartment/apartment7.jpeg",
                },
                {
                    imageId: 7,
                    imageActive: false,
                    imagePath: "images/apartment/apartment8.jpeg",
                },
                {
                    imageId: 8,
                    imageActive: false,
                    imagePath: "images/apartment/apartment9.jpeg",
                },
            ],
            facilities: "<h3>Kitchen</h3><h3>TV</h3><h3>Parking Lot</h3><h3>Internet</h3><h3>Swimming Pool</h3><h3>Gym</h3>",
            address: "<p>Arandra Residence, Jl. Cempaka Putih Raya No.1 1, RT.1/RW.6, Cemp. Putih Tim., Kec. Cemp. Putih, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10510</p>",
            mapEmbed: "<div class=\"d-flex\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.6588164421305!2d106.86277427404326!3d-6.176408293810982!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f5c710564caf%3A0xa4e127f3926de7ed!2sArandra%20Residence%20Official!5e0!3m2!1sen!2sid!4v1719059907503!5m2!1sen!2sid\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe></div>",
        },
    ],
}

const galleryPage = {
    images: [
        {
            id: 0,
            imagePath: "images/gallery/terrace1.jpg",
            dataFilter: "terrace",
            altText: "Terrace Image",
        },
        {
            id: 1,
            imagePath: "images/gallery/terrace2.jpg",
            dataFilter: "terrace",
            altText: "Terrace Image",
        },
        {
            id: 2,
            imagePath: "images/gallery/terrace3.jpg",
            dataFilter: "terrace",
            altText: "Terrace Image",
        },
        {
            id: 3,
            imagePath: "images/gallery/terrace4.jpg",
            dataFilter: "terrace",
            altText: "Terrace Image",
        },
        {
            id: 4,
            imagePath: "images/gallery/terrace5.jpeg",
            dataFilter: "terrace",
            altText: "Terrace Image",
        },
        {
            id: 5,
            imagePath: "images/gallery/livingRoom1.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 6,
            imagePath: "images/gallery/livingRoom2.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 7,
            imagePath: "images/gallery/livingRoom3.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 8,
            imagePath: "images/gallery/livingRoom4.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 9,
            imagePath: "images/gallery/livingRoom5.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 10,
            imagePath: "images/gallery/livingRoom6.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 11,
            imagePath: "images/gallery/livingRoom7.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 12,
            imagePath: "images/gallery/livingRoom8.jpg",
            dataFilter: "living-room",
            altText: "Living Room Image",
        },
        {
            id: 13,
            imagePath: "images/gallery/sideGarden1.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 14,
            imagePath: "images/gallery/sideGarden2.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 15,
            imagePath: "images/gallery/sideGarden3.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 16,
            imagePath: "images/gallery/sideGarden4.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 17,
            imagePath: "images/gallery/sideGarden5.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 18,
            imagePath: "images/gallery/sideGarden6.jpeg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 19,
            imagePath: "images/gallery/sideGarden7.jpg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 20,
            imagePath: "images/gallery/sideGarden8.jpg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 21,
            imagePath: "images/gallery/sideGarden9.jpg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 22,
            imagePath: "images/gallery/sideGarden10.jpg",
            dataFilter: "side-garden",
            altText: "Side Garden Image",
        },
        {
            id: 23,
            imagePath: "images/gallery/upstairs1.jpeg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 24,
            imagePath: "images/gallery/upstairs2.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 25,
            imagePath: "images/gallery/upstairs3.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 26,
            imagePath: "images/gallery/upstairs4.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 27,
            imagePath: "images/gallery/upstairs5.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 28,
            imagePath: "images/gallery/upstairs6.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 29,
            imagePath: "images/gallery/upstairs7.jpeg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 30,
            imagePath: "images/gallery/upstairs8.jpeg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 31,
            imagePath: "images/gallery/upstairs9.jpg",
            dataFilter: "upstairs",
            altText: "Upstairs Image",
        },
        {
            id: 32,
            imagePath: "images/gallery/kitchen1.jpg",
            dataFilter: "kitchen",
            altText: "Kitchen Image",
        },
        {
            id: 33,
            imagePath: "images/gallery/kitchen2.jpg",
            dataFilter: "kitchen",
            altText: "Kitchen Image",
        },
        {
            id: 34,
            imagePath: "images/gallery/kitchen3.jpg",
            dataFilter: "kitchen",
            altText: "Kitchen Image",
        },
        {
            id: 35,
            imagePath: "images/gallery/kitchen4.jpg",
            dataFilter: "kitchen",
            altText: "Kitchen Image",
        },
        {
            id: 36,
            imagePath: "images/gallery/kitchen5.jpg",
            dataFilter: "kitchen",
            altText: "Kitchen Image",
        },
        {
            id: 37,
            imagePath: "images/gallery/parkingLot1.jpeg",
            dataFilter: "parking-lot",
            altText: "Parking Lot Image",
        },
        {
            id: 38,
            imagePath: "images/gallery/parkingLot2.jpeg",
            dataFilter: "parking-lot",
            altText: "Parking Lot Image",
        },
        {
            id: 39,
            imagePath: "images/gallery/parkingLot3.jpeg",
            dataFilter: "parking-lot",
            altText: "Parking Lot Image",
        },
        {
            id: 40,
            imagePath: "images/guestHouse/guestHouse1.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 41,
            imagePath: "images/guestHouse/guestHouse2.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 42,
            imagePath: "images/guestHouse/guestHouse3.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 43,
            imagePath: "images/guestHouse/guestHouse4.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 44,
            imagePath: "images/guestHouse/guestHouse5.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 45,
            imagePath: "images/guestHouse/guestHouse6.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 46,
            imagePath: "images/guestHouse/guestHouse7.jpeg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 47,
            imagePath: "images/guestHouse/guestHouse8.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 48,
            imagePath: "images/guestHouse/guestHouse9.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 49,
            imagePath: "images/guestHouse/guestHouse10.jpg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 50,
            imagePath: "images/guestHouse/guestHouse11.jpeg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 51,
            imagePath: "images/guestHouse/guestHouse12.jpeg",
            dataFilter: "guest-house",
            altText: "Guest House Image",
        },
        {
            id: 52,
            imagePath: "images/guestHouseVIP/guestHouseVIP1.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 53,
            imagePath: "images/guestHouseVIP/guestHouseVIP2.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 54,
            imagePath: "images/guestHouseVIP/guestHouseVIP3.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 55,
            imagePath: "images/guestHouseVIP/guestHouseVIP4.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 56,
            imagePath: "images/guestHouseVIP/guestHouseVIP5.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 57,
            imagePath: "images/guestHouseVIP/guestHouseVIP6.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 58,
            imagePath: "images/guestHouseVIP/guestHouseVIP7.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 59,
            imagePath: "images/guestHouseVIP/guestHouseVIP8.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 60,
            imagePath: "images/guestHouseVIP/guestHouseVIP9.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 61,
            imagePath: "images/guestHouseVIP/guestHouseVIP10.jpg",
            dataFilter: "guest-house-vip",
            altText: "Guest House VIP Image",
        },
        {
            id: 62,
            imagePath: "images/dormitory/dormitory1.jpeg",
            dataFilter: "dormitory",
            altText: "Dormitory Image",
        },
        {
            id: 63,
            imagePath: "images/dormitory/dormitory2.jpeg",
            dataFilter: "dormitory",
            altText: "Dormitory Image",
        },
        {
            id: 64,
            imagePath: "images/dormitory/dormitory3.jpeg",
            dataFilter: "dormitory",
            altText: "Dormitory Image",
        },
        {
            id: 65,
            imagePath: "images/dormitory/dormitory4.jpeg",
            dataFilter: "dormitory",
            altText: "Dormitory Image",
        },
        {
            id: 66,
            imagePath: "images/dormitory/dormitory5.jpeg",
            dataFilter: "dormitory",
            altText: "Dormitory Image",
        },
        {
            id: 67,
            imagePath: "images/apartment/apartment1.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 68,
            imagePath: "images/apartment/apartment2.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 69,
            imagePath: "images/apartment/apartment3.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 70,
            imagePath: "images/apartment/apartment4.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 71,
            imagePath: "images/apartment/apartment5.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 72,
            imagePath: "images/apartment/apartment6.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 73,
            imagePath: "images/apartment/apartment7.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 74,
            imagePath: "images/apartment/apartment8.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
        {
            id: 75,
            imagePath: "images/apartment/apartment9.jpeg",
            dataFilter: "apartment",
            altText: "Apartment Image",
        },
    ],
}